---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: secondary-flux-repo
  namespace: apps
spec:
  gitImplementation: go-git
  interval: 1m0s
  ref:
    branch: main
  # secretRef:
  #   name: secondary-flux-repo
  timeout: 60s
  url: https://github.com/kalioz/fluxv2-demo-tenant-repo.git # ssh://git@github.com/kalioz/fluxv2-demo-tenant-repo.git
