---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: sealed-secrets
      version: '2.5.2'
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
        namespace: flux-system
      interval: 1m
  values:
